import { defineType, defineField } from "sanity";

export const product = defineType({
  name: "product",
  title: "Product",
  type: "document",
  fields: [
    defineField({ name: "name",        title: "Name",         type: "string" }),
    defineField({ name: "slug",        title: "Slug",         type: "slug",
      options: { source: "name", maxLength: 96 } }),
    defineField({ name: "category",    title: "Category",     type: "string",
      options: { list: ["WHOLE BEAN","GROUND","LIGHT ROAST","MEDIUM","DARK","ESPRESSO","GREEN/UNROASTED"] } }),
    defineField({ name: "badgeLabel",  title: "Badge Label (override)", type: "string" }),
    defineField({ name: "varietal",    title: "Varietal",     type: "string" }),
    defineField({ name: "scaScore",    title: "SCA Score",    type: "number" }),
    defineField({ name: "process",     title: "Process",      type: "string" }),
    defineField({ name: "flavorNotes", title: "Flavor Notes", type: "string" }),
    defineField({ name: "weight",      title: "Weight",       type: "string" }),
    defineField({ name: "priceFrom",   title: "Price From",   type: "number" }),
    defineField({ name: "currency",    title: "Currency",     type: "string",
      initialValue: "KES" }),
    defineField({ name: "image",       title: "Main Image",   type: "image",
      options: { hotspot: true },
      fields: [defineField({ name: "alt", type: "string", title: "Alt Text" })] }),
    defineField({ name: "backImage",   title: "Back Image (optional)", type: "image",
      fields: [defineField({ name: "alt", type: "string", title: "Alt Text" })] }),
    defineField({ name: "profile",     title: "Flavor Profile",  type: "string" }),
    defineField({ name: "altitude",    title: "Altitude (masl)", type: "string" }),
    defineField({ name: "roastProfile",title: "Roast Profile",   type: "string" }),
    defineField({ name: "farm",        title: "Farm / Origin",   type: "string" }),
    defineField({ name: "description", title: "Description",     type: "text" }),
    defineField({ name: "order",       title: "Display Order",   type: "number",
      hidden: true }),
  ],
  orderings: [{ title: "Display Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: {
    select: { title: "name", subtitle: "category", media: "image" },
  },
});
